name: flutter_project_bdclpm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  iconly: ^1.0.1
  carousel_slider: ^5.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  code_coverage: ^1.4.0
  fl_chart: ^0.70.1
  firebase_storage: ^12.4.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  gcloud: ^0.8.18
  mime: ^2.0.0
  cloud_firestore: ^5.6.1
  diacritic: ^0.1.6
  speech_to_text: ^7.0.0
  file_picker: ^8.1.7
  pdf: ^3.11.1
  excel: ^4.0.6
  flutter_pdfview: ^1.4.0
  syncfusion_flutter_pdf: ^28.1.39
  intl: ^0.19.0
  table_calendar: ^3.1.3
  flutter_echarts: ^2.5.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.18.0
  font_awesome_flutter: ^10.8.0
  firebase_auth_mocks: ^0.14.1
  flutter_web_auth_2: ^4.1.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  mockito: ^5.4.5
  test: ^1.25.8
  json_serializable: ^6.9.3
  bloc_test: ^10.0.0
  freezed_annotation: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/hinh1.png
    - assets/images/h2.png
    - assets/icons/
    - assets/key/
    - assets/key/credentials.json
