// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlJGTRo7JwMUyhThSo4EW2ePVROKCkcOk',
    appId: '1:754581994744:web:3abe6d649fb2db35c34f0d',
    messagingSenderId: '754581994744',
    projectId: 'project-5e8d1',
    authDomain: 'project-5e8d1.firebaseapp.com',
    storageBucket: 'project-5e8d1.firebasestorage.app',
    measurementId: 'G-C5ZF5GC936',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG2DndyK3KiqdJsekInHsn4nbJYVrJLh4',
    appId: '1:754581994744:android:2d40b68495e614a8c34f0d',
    messagingSenderId: '754581994744',
    projectId: 'project-5e8d1',
    storageBucket: 'project-5e8d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdE_pZ2eveizLdqAqaMDvb5h_UqaDuUo',
    appId: '1:754581994744:ios:32eb4c40df55c65bc34f0d',
    messagingSenderId: '754581994744',
    projectId: 'project-5e8d1',
    storageBucket: 'project-5e8d1.firebasestorage.app',
    iosClientId: '754581994744-1dvsm6tgb0fhfe61ing9nu9m2kkcsrmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBdclpm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUdE_pZ2eveizLdqAqaMDvb5h_UqaDuUo',
    appId: '1:754581994744:ios:32eb4c40df55c65bc34f0d',
    messagingSenderId: '754581994744',
    projectId: 'project-5e8d1',
    storageBucket: 'project-5e8d1.firebasestorage.app',
    iosClientId: '754581994744-1dvsm6tgb0fhfe61ing9nu9m2kkcsrmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjectBdclpm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlJGTRo7JwMUyhThSo4EW2ePVROKCkcOk',
    appId: '1:754581994744:web:75b164e58a8ec357c34f0d',
    messagingSenderId: '754581994744',
    projectId: 'project-5e8d1',
    authDomain: 'project-5e8d1.firebaseapp.com',
    storageBucket: 'project-5e8d1.firebasestorage.app',
    measurementId: 'G-RXSSYWRVKN',
  );
}
